# Generated by Django 2.1 on 2021-07-28 22:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0012_comment_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment1',
        ),
    ]
